version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./backend/relatorios:/app/relatorios
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - TRANSPORT=sse
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge 